import React, {useEffect, useState} from 'react';
import {Timeline} from 'react-twitter-widgets'
import { getTopStories, submitRating } from '../../service/stories';

export default function Homepage(props) {
    const [topStories, setTopStories] = useState([]);
    const [loadError, setLoadError] = useState(false);
    const [submittedRating, setSubmittedRating] = useState(false);

    const handleRatingSubmit = async(e) => {
        e.preventDefault();
        const ratingInfo = {
            story_id: e.target.elements.story_id.value,
            rating: e.target.elements.rating.value
        }
        submitRating(ratingInfo, props.token)
        .then(() => {
            setSubmittedRating(!submittedRating)
        })
        .catch(err => {
            console.log(err);
        }) 
    }

    useEffect(function effectFunction() {
        getTopStories()
        .then((data) => {
            console.log(data)
            setTopStories(data);
            setLoadError(false)
        })
        .catch(err => {
            setLoadError(true);
        })
        return () => {
            setTopStories([]);
            setLoadError();
        }
    }, [submittedRating])

    return(
        <div>
            <h1>Homepage</h1>
            <h2>Welcome, {props.user.first_name}!</h2>
            <div className="container">
                <div className="row">
                    <div className="col">
                        <h3>Top Stories</h3>
                        {loadError && <p color="red">Error Loading Stories!</p>}
                    {(() => {
                        let storyCards = []
                        for(let i = 0; i < topStories.length; i++) {
                            let story = topStories[i]
                            storyCards.push(
                                <div className="card mb-2" key={i}>
                                    <h5 className="card-title m-2">{story.title}</h5>
                                    <h6 className="card-subtitle m-2 text-muted">Generated By: {story.email}</h6>
                                    <h6 className="card-subtitle m-2 text-muted">Average Rating: {parseFloat(story.average_rating).toFixed(2)}</h6>
                                    <p className="card-text m-2">{story.text}</p>
                                    <form onSubmit={handleRatingSubmit}>
                                        <div className="m-2">
                                            <input type="text" hidden readOnly className="form-control" id="story_id" value={story.story_id}/>
                                        </div>
                                        <div className="m-2">
                                            <label htmlFor="rating" className="form-label">Rate This Story</label>
                                            <select id="rating" defaultValue={1} className="form-select">
                                                <option value={1}>1</option>
                                                <option value={2}>2</option>
                                                <option value={3}>3</option>
                                                <option value={4}>4</option>
                                                <option value={5}>5</option>
                                            </select>
                                        </div>
                                        <button type="submit" className="btn btn-success m-2">Rate It!</button>
                                    </form>
                                </div>
                            )

                        }
                        return (storyCards);
                    })()}
                    </div>
                    <div className="col">
                        <h3>Twitter Bot Feed</h3>

                        <div className="card">
                            <Timeline
                                dataSource={{
                                    sourceType: 'profile',
                                    screenName: 'ai_bot_stories'
                                }}

                            />
                        </div>

                    </div>

                </div>

            </div>
        </div>
        
    );
}